plugins:
    - jekyll-seo-tag

title: James D. | Profile
tagline: The professional profile of James D.
description: |
    Hello, I'm James. 
    Since 2013, I've been working with Australia's premier Intelligent Transport System solution vendor. 
    Designing and building highly maintainable software solutions is one of my passions. 
    My capacity to swiftly learn and use new technology is my greatest asset. 
    I also have a talent for identifying the source of problems and devising effective solutions.
url: jamesd24.github.io
author: James D.
my_roles: Senior Software Engineer, Problem Solver
location: Brisbane, QLD, Australia
